{
  "sksl": {
    "entrypoint": "flashlight_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float uTime;\nuniform vec2 uMouse;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uResolution;\n    bool _35 = uMouse.x >= 0.0;\n    bool _42;\n    if (_35)\n    {\n        _42 = uMouse.x <= 1.0;\n    }\n    else\n    {\n        _42 = _35;\n    }\n    bool _49;\n    if (_42)\n    {\n        _49 = uMouse.y >= 0.0;\n    }\n    else\n    {\n        _49 = _42;\n    }\n    bool _55;\n    if (_49)\n    {\n        _55 = uMouse.y <= 1.0;\n    }\n    else\n    {\n        _55 = _49;\n    }\n    if (!_55)\n    {\n        fragColor = vec4(uTexture.eval(uTexture_size * ( uv)).xyz * 0.20000000298023223876953125, 1.0);\n        return;\n    }\n    vec4 originalColor = uTexture.eval(uTexture_size * ( uv));\n    float aspect_ratio = uResolution.x / uResolution.y;\n    vec2 uv_ndc = ((uv * 2.0) - vec2(1.0)) * vec2(aspect_ratio, 1.0);\n    vec2 mouse_ndc = ((uMouse * 2.0) - vec2(1.0)) * vec2(aspect_ratio, 1.0);\n    float dist_to_mouse = length(uv_ndc - mouse_ndc);\n    float finalIntensity = exp(-(dist_to_mouse * 6.0)) * 3.0;\n    vec4 darkColor = vec4(originalColor.xyz * 0.20000000298023223876953125, 1.0);\n    vec4 brightColor = originalColor;\n    fragColor = mix(darkColor, brightColor, vec4(finalIntensity));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uMouse",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 3,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}