{
  "sksl": {
    "entrypoint": "ripple_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float uTime;\nuniform vec2 uClickPosition;\nuniform float uClickTime;\nuniform shader uImage;\nuniform half2 uImage_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uResolution;\n    float timeSinceClick = uTime - uClickTime;\n    if ((uClickPosition.x < 0.0) || (timeSinceClick > 2.0))\n    {\n        fragColor = uImage.eval(uImage_size * ( uv));\n    }\n    vec2 click_uv = uClickPosition;\n    vec2 distVec = uv - click_uv;\n    float dist = length(distVec);\n    float wave_speed = 1.5;\n    float wave_strength = 0.00999999977648258209228515625;\n    float wave_pos = dist - (timeSinceClick * wave_speed);\n    float ripple = (sin(wave_pos * 20.0) * wave_strength) * (1.0 - smoothstep(0.0, 1.0, timeSinceClick / 2.0));\n    vec2 offsetUV = uv + (normalize(distVec) * ripple);\n    fragColor = uImage.eval(uImage_size * ( offsetUV));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uImage",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uClickPosition",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uClickTime",
        "rows": 1,
        "type": 10
      }
    ]
  }
}